---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - cowsay
  - doxygen
  - dockutil
  - fish
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - libgit2
  - openssl
  - pv
  - mcrypt
  - mas
  - nano
  - nmap
  - node
  - nvm
  - python
  - r
  - readline
  - sqlite
  - ssh-copy-id
  - tmux
  - unixodbc # helps with the R package `odbc`
  - wget
  - wrk
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - anaconda # might need to run `export PATH=/usr/local/anaconda3/bin:"$PATH"` to make it work
  - backblaze
  - bbedit
  - basictex
  - capture-one
  - chromedriver
  - docker
  - dropbox 
  - fantastical
#  - google-chrome
  - handbrake
  - iterm2
  - java8
  - licecap
  - logitech-unifying
  - logitech-control-center
  - macdown
  - macvim
  - pycharm-ce
  - rstudio
  - sequel-pro
  - sketchup
  - skitch
#  - slack
  - sourcetree
  - sublime-text
  - textexpander
  - vlc


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 918858936, name: "Airmail 3"}
  - { id: 961632517, name: "Be Focused Pro"}
  - { id: 1091189122, name: "Bear"}
  - { id: 409222199, name: "Cyberduck"}
  - { id: 975937182, name: "Fantastical 2"}
  - { id: 1189824719, name: "Jayson"}
  - { id: 441258766, name: "Magnet"}
  - { id: 920404675, name: "Monodraw"}
  - { id: 867299399, name: "OmniFocus 2"}
  - { id: 1142578772, name: "OmniOutliner"}
  - { id: 1179623856, name: "Pastebot"}
  - { id: 1153157709, name: "Speedtest"}
  - { id: 985614903, name: "SQLPro Studio"}
  - { id: 534067900, name: "Stock + Pro"}
  - { id: 497799835, name: "Xcode"}
mas_email: "benjoaquin@mac.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: 
  - name: mkdocs
    state: present # present/absent/latest, default: present
    version: "0.16.3" # default: N/A
  - name: h5py
    state: present
  - name: keras  # `--upgrade --ignore-installed six` helps with `distutils installed project` error
    state: present
  - name: tensorflow
    state: present

dockitems_remove_all: true
dockitems_enabled:
  - name: Terminal
    path: "/Applications/Utilities/Terminal.app"
    pos: 1
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 2

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []


## Things I've installed manually ===========================
# * Latex Live - http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
# * FUJIFILM X RAW STUDIO - http://www.fujifilm.com/support/digital_cameras/software/x_raw_studio/mac/
# * Fujifilm ICC profiles for Capture One - https://blog.thomasfitzgeraldphotography.com/blog/2017/2/how-to-download-and-install-fuji-colour-profiles-for-capture-one
# * Additional Tools for Xcode - https://download.developer.apple.com/Developer_Tools/Additional_Tools_for_Xcode_10_Beta/Additional_Tools_for_Xcode_10_Beta.dmg
# * Oh my ZSH - `sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"`

